version: '2'

volumes:
    pgdata:

services:
    db:
        image: postgres:9.6-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user
            POSTGRES_DB: db
        volumes:
            - pgdata:/var/lib/postgresql/data